language: rust

matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
      cache: cargo
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      cache: cargo

sudo: false

script:
  - cargo test --target $TARGET --features no_std
  - cargo test --target $TARGET

notifications:
  email:
    on_success: never
